# Input/output configuration
input_dir: ${SCRATCH}/LRT/v3/pileup40/feature_store
output_dir: ${SCRATCH}/LRT/v3/pileup40/embedding_processed
project: LRT_embedding
overwrite: True

# Dataset parameters
pt_signal_cut: 1.0
pt_background_cut: 0.0
eta_signal_cut: 4.0
train_split: [[4000, 500, 500]] # Number of [training, validation, testing] examples
true_edges: layerless_true_edges
noise: True

# Model parameters
spatial_channels: 3
cell_channels: 0
emb_hidden: 1024
nb_layer: 8
emb_dim: 8
weight: 10
activation: Tanh
randomisation: 2
points_per_batch: 100000
r_train: 0.8
r_test: 0.8
r_val: 0.8
knn: 20
warmup: 80
margin: 0.8
lr: 0.0001
factor: 0.3
patience: 10
regime: [[rp, hnm]]
max_epochs: 0

# Inference
# checkpoint_path: lightning_checkpoints/LRT_embedding/version_31/checkpoints/last.ckpt
# resume_id: 31
r_build: 0.3
k_build: 500

# Postprocessing
callbacks: [[EmbeddingTelemetry, EmbeddingBuilder]]
