# Input/output configuration
input_dir: ${SCRATCH}/LRT/v3/pileup40/embedding_processed
output_dir: ${SCRATCH}/LRT/v3/pileup40/filter_processed
project: LRT_filter
edge_cut: 0.05
overwrite: True

# Dataset parameters
pt_background_min: 0.
pt_signal_min: 1.
eta_signal_max: 4.
datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [[4000, 500, 500]] # Number of [training, validation, testing] examples
endcaps: True
true_edges: layerless_true_edges
noise: True

# Model parameters
spatial_channels: 3
cell_channels: 0
hidden: 1024
hidden_activation: Tanh
nb_layer: 5
emb_channels: 0
layernorm: True
batchnorm: False
n_chunks: 12
edges_per_batch: 3000000
ratio: 8
weight: 8
warmup: 200
lr: 0.000001
factor: 0.3
patience: 12
regime: [[rp, hnm]]
max_epochs: 0

# Post-processing
callbacks: [[FilterBuilder]]
