# Input/output configuration
input_dir: ${SCRATCH}/LRT/v3/pileup40/embedding_processed_pyg2
output_dir: ${SCRATCH}/LRT/v3/pileup40/filter_processed
project: LRT_filter
edge_cut: 0.2
overwrite: True

# Dataset parameters
pt_background_min: 0.
pt_signal_min: 1.
datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [[4000, 500, 500]] # Number of [training, validation, testing] examples
endcaps: True
true_edges: layerless_true_edges
noise: True

# Model parameters
spatial_channels: 3
cell_channels: 0
hidden: 1024
hidden_activation: Tanh
nb_layer: 4
emb_channels: 0
layernorm: True
batchnorm: False
n_chunks: 2
edges_per_batch: 3000000
ratio: 8
weight: 8
warmup: 10
lr: 0.02
factor: 0.7
patience: 20
regime: [[]]
max_epochs: 0

# Post-processing
callbacks: [[FilterBuilder, FilterTelemetry]]

