# Input/output configuration
input_dir: ${SCRATCH}/LRT/v3/pileup40/filter_processed
output_dir: ${SCRATCH}/LRT/v3/pileup40/gnn_processed
project: LRT_GNN
edge_cut: 0.5

# Dataset parameters
pt_signal_min: 1.
pt_background_min: 0.
eta_signal_max: 4.
datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [[4000, 500, 500]] # Number of [training, validation, testing] examples
true_edges: layerless_true_edges
noise: False

# Model parameters
# spatial_channels: 3
in_channels: 3
cell_channels: 0
hidden: 128
n_graph_iters: 8
nb_node_layer: 3
nb_edge_layer: 3
emb_channels: 0
layernorm: True
aggregation: sum_max
hidden_activation: ReLU
weight: 2
warmup: 200
lr: 0.001
factor: 0.3
patience: 10
regime: [[pid]]
max_epochs: 30

# Post-processing
callbacks: [[GNNTelemetry, GNNBuilder]]
